---
title: "reproducible_research_assignment_1"
author: "ABS"
date: "Tuesday, August 05, 2014"
output: html_document
---

```{r readdata}


``` 


#data without missing value



mean total number of steps taken per day
```{r plot_the_mean}
library(ggplot2)
data1<-read.csv("activity.csv");
data<-data1;
complete<-data1[complete.cases(data1),];

histo<-aggregate(list(complete$steps),list(complete$date),sum);
histo<-cbind(histo,1:nrow(histo))

names(histo)<-c("date","steps","count");
plot_1<-ggplot(histo,aes(count,steps));
plot_1<-plot_1+ geom_bar(stat="identity",colour="red",fill="red");
plot_1;
mean_number = mean(histo$steps)
median_number = median(histo$steps)
print("mean: ");print(mean_number)
print("media: ");print(median_number)
```


average daily activity pattern
```{r  average daily activity pattern}
series<-aggregate(complete$steps,list(complete$interval),sum)
names(series)<-c("interval","steps")
plot_2 <- ggplot(series,aes(interval,steps))
plot_2+geom_line()
```

the max interval throughout all days
```{r max interval}
print(series[series$steps==max(series$steps),"interval"])

```




number of NAs
```{r NA}
nrow(data)-sum(complete.cases(data))

```

#The data with Nas replaced by ZERO
```{r}
data1<-read.csv("activity.csv")
log<-complete.cases(data1)
data1[!log,"steps"]<-0
complete<-data1[complete.cases(data1),];

histo<-aggregate(list(complete$steps),list(complete$date),sum);
histo<-cbind(histo,1:nrow(histo))

names(histo)<-c("date","steps","count");
plot_1<-ggplot(histo,aes(count,steps));
plot_1<-plot_1+ geom_bar(stat="identity",colour="red",fill="red");
plot_1;
mean_number = mean(histo$steps)
median_number = median(histo$steps)
print("mean: ");print(mean_number)
print("media: ");print(median_number)

series<-aggregate(complete$steps,list(complete$interval),sum)
names(series)<-c("interval","steps")
plot_2 <- ggplot(series,aes(interval,steps))
plot_2+geom_line()


```
#conclusion: of course, ZEROS lower the mean so the plots are changed. But the shape of the series doesn't change and just be shorter.


```{r}
data1<-read.csv("activity.csv");
data<-data1;
complete<-data1[complete.cases(data1),];
#for chinese
log_weekdays<-week_list =="星期四" | week_list =="星期三" | week_list =="星期二" | 
week_list =="星期一" | week_list =="星期五"
#for english

#log_weekdays<-week_list =="Thursday" | week_list =="Wednesday" | week_lis=="Tuesday" | week_list =="Monday" | week_list =="Friday"

temp<-rep("weekends",nrow(complete))
temp[log_weekdays]<-"weekday"
new<-cbind(temp,complete)

plot_5_data<-aggregate(new$steps,list(new$temp,new$interval),mean)
names(plot_5_data)<-c("temp","interval","steps")
qplot(interval,steps,data=plot_5_data,facets=.~temp,geom = c("line"))

```

